export const styles: Record<string, Record<string, string>> = {
  container: {
    position: 'fixed',
    bottom: '20px',
    left: '20px',
    zIndex: '99999',
    fontFamily: "'Tajawal', 'Segoe UI', sans-serif",
    direction: 'rtl',
  },
  toggleBtn: {
    width: '60px',
    height: '60px',
    borderRadius: '50%',
    background: '#1a1a2e',
    color: '#fff',
    border: 'none',
    fontSize: '28px',
    cursor: 'pointer',
    boxShadow: '0 4px 20px rgba(0,0,0,0.3)',
    transition: 'transform 0.2s',
  },
  chatWindow: {
    width: '380px',
    height: '560px',
    borderRadius: '16px',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    background: '#ffffff',
    boxShadow: '0 8px 40px rgba(0,0,0,0.2)',
    border: '1px solid #e5e7eb',
  },
  header: {
    background: '#1a1a2e',
    color: '#ffffff',
    padding: '14px 18px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontWeight: '700',
    fontSize: '16px',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  statusDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    display: 'inline-block',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    color: '#ffffff',
    fontSize: '18px',
    cursor: 'pointer',
    padding: '0',
  },
  messagesArea: {
    flex: '1',
    overflowY: 'auto',
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    background: '#fafafa',
  },
  inputArea: {
    display: 'flex',
    alignItems: 'center',
    padding: '10px 12px',
    borderTop: '1px solid #e5e7eb',
    gap: '8px',
    background: '#ffffff',
  },
  textInput: {
    flex: '1',
    border: '1px solid #d1d5db',
    borderRadius: '24px',
    padding: '10px 16px',
    fontSize: '14px',
    outline: 'none',
    fontFamily: 'inherit',
    direction: 'rtl',
  },
  sendBtn: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    background: '#1a1a2e',
    color: '#ffffff',
    border: 'none',
    fontSize: '18px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transform: 'scaleX(-1)',
  },
  attachBtn: {
    background: 'none',
    border: 'none',
    fontSize: '20px',
    cursor: 'pointer',
    padding: '4px',
  },
  listContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    marginBottom: '12px',
    paddingRight: '8px',
  },
  listItem: {
    padding: '10px 14px',
    borderRadius: '10px',
    border: '1px solid #e5e7eb',
    background: '#ffffff',
    textAlign: 'right',
    cursor: 'pointer',
    fontSize: '13px',
    fontFamily: 'inherit',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    transition: 'background 0.2s',
  },
  listDesc: {
    color: '#6b7280',
    fontSize: '12px',
  },
};
